spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knowhub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    issuer: knowhub
    secret: 3d2b4f5e7a8c901234567890abcdef1234567890abcdef1234567890abcdef
    accessTtlMinutes: 30
    refreshTtlDays: 7

server:
  port: 8080
  forward-headers-strategy: native
