FROM node:20 AS build
WORKDIR /app
COPY ../frontend /app
RUN npm i --silent && npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
