version: "3.9"
services:
  db:
    image: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_DATABASE: knowhub
      MYSQL_USER: knowhub
      MYSQL_PASSWORD: knowhub_pw
      MYSQL_ROOT_PASSWORD: root_pw
    volumes:
      - db_data:/var/lib/mysql
    networks: [lan]

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/knowhub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: knowhub
      SPRING_DATASOURCE_PASSWORD: knowhub_pw
      APP_JWT_SECRET: change_me_super_secret
    depends_on: [db]
    networks: [lan]

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on: [api]
    ports:
      - "8080:80"
    networks: [lan]

volumes:
  db_data:

networks:
  lan:
