spring:
  datasource:
    url: jdbc:mysql://db:3306/knowhub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    issuer: knowhub
    secret: change_me_super_secret
    accessTtlMinutes: 30
    refreshTtlDays: 7

server:
  port: 8080
  forward-headers-strategy: native
